/* ─────────────────────────────────────────────
   SHARED DATA — ANACHRONA
───────────────────────────────────────────── */

export const UNIVERSE_COLORS = {
  rome: '#c0392b',
  'rois-france': '#c9a84c',
  'femmes-pouvoir': '#8e44ad',
  'legendes-mers': '#1a6b8a',
  'legendes-asie': '#27ae60',
  philosophes: '#7f8c8d',
  'mythologie-grecque': '#1a237e',
};

export const UNIVERSES = [
  {
    id: 'rome',
    name: 'Rome',
    icon: 'ROME',
    color: '#c0392b',
    sub: "L'Empire Éternel",
    heroText: "Fascinante et impitoyable, Rome façonna le monde occidental par sa loi, ses armées et son génie civil. Empereurs, généraux et conspirateurs se disputèrent le trône dans un ballet de grandeur et de sang.",
    pattern: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='120'%3E%3Ctext x='10' y='45' font-family='Georgia%2C serif' font-size='14' fill='rgba(192%2C57%2C43%2C.07)' font-weight='bold'%3ESPQR%3C/text%3E%3Ctext x='60' y='90' font-family='Georgia%2C serif' font-size='14' fill='rgba(192%2C57%2C43%2C.07)' font-weight='bold'%3ESPQR%3C/text%3E%3C/svg%3E")`,
  },
  {
    id: 'rois-france',
    name: 'Rois de France',
    icon: 'REX',
    color: '#c9a84c',
    sub: 'La Couronne & le Destin',
    heroText: "Mille ans de monarchie, d'intrigues de cour et de gloire impérissable. Des Carolingiens aux Bourbons, les rois de France tracèrent le destin d'une nation entre guerres, alliances et révolutions.",
    pattern: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='80' height='80'%3E%3Cpath d='M18 54 L18 36 L28 44 L40 20 L52 44 L62 36 L62 54 Z' fill='none' stroke='rgba(201%2C168%2C76%2C.09)' stroke-width='1.3'/%3E%3C/svg%3E")`,
  },
  {
    id: 'femmes-pouvoir',
    name: 'Femmes de Pouvoir',
    icon: 'REGINA',
    color: '#8e44ad',
    sub: "Celles qui ont changé l'Histoire",
    heroText: "Reines, guerrières, régentes et visionnaires : elles exercèrent le pouvoir dans des sociétés qui leur refusaient ce droit. Leur audace, leur intelligence et leur courage remodelèrent le cours de l'Histoire.",
    pattern: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='80' height='80'%3E%3Ccircle cx='40' cy='40' r='28' fill='none' stroke='rgba(142%2C68%2C173%2C.09)' stroke-width='1'/%3E%3Ccircle cx='40' cy='40' r='18' fill='none' stroke='rgba(142%2C68%2C173%2C.07)' stroke-width='1'/%3E%3Cline x1='40' y1='12' x2='40' y2='68' stroke='rgba(142%2C68%2C173%2C.06)' stroke-width='1'/%3E%3Cline x1='12' y1='40' x2='68' y2='40' stroke='rgba(142%2C68%2C173%2C.06)' stroke-width='1'/%3E%3C/svg%3E")`,
  },
  {
    id: 'legendes-mers',
    name: 'Légendes des Mers',
    icon: 'MARE',
    color: '#1a6b8a',
    sub: "Les conquérants de l'Océan",
    heroText: "Corsaires, explorateurs et amiraux qui défiaient les tempêtes et l'inconnu. Leurs voyages tracèrent de nouvelles routes commerciales, découvrirent des continents et redéfinirent les frontières du monde connu.",
    pattern: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100'%3E%3Ccircle cx='50' cy='50' r='30' fill='none' stroke='rgba(26%2C107%2C138%2C.09)' stroke-width='1'/%3E%3Cline x1='50' y1='20' x2='50' y2='80' stroke='rgba(26%2C107%2C138%2C.08)' stroke-width='1'/%3E%3Cline x1='20' y1='50' x2='80' y2='50' stroke='rgba(26%2C107%2C138%2C.08)' stroke-width='1'/%3E%3Cline x1='29' y1='29' x2='71' y2='71' stroke='rgba(26%2C107%2C138%2C.06)' stroke-width='1'/%3E%3Cline x1='71' y1='29' x2='29' y2='71' stroke='rgba(26%2C107%2C138%2C.06)' stroke-width='1'/%3E%3C/svg%3E")`,
  },
  {
    id: 'legendes-asie',
    name: "Légendes d'Asie",
    icon: '東方',
    color: '#27ae60',
    sub: "Les titans de l'Orient",
    heroText: "De la steppe mongole aux dojos japonais, en passant par les cours impériales de Chine, l'Asie a enfanté des stratèges, des guerriers et des philosophes dont la légende traverse les millénaires.",
    pattern: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='80' height='80'%3E%3Ctext x='12' y='58' font-family='serif' font-size='44' fill='rgba(39%2C174%2C96%2C.07)'%3E%E9%BE%8D%3C/text%3E%3C/svg%3E")`,
  },
  {
    id: 'philosophes',
    name: 'Philosophes',
    icon: 'SOPHIA',
    color: '#7f8c8d',
    sub: 'Penseurs & Sages',
    heroText: "Ils ne conquirent pas des territoires mais des esprits. Par la dialectique, l'écriture et l'action politique, philosophes et penseurs posèrent les fondements de notre civilisation et de notre façon de concevoir le monde.",
    pattern: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='80' height='80'%3E%3Crect x='12' y='40' width='8' height='28' rx='1' fill='rgba(127%2C140%2C141%2C.1)'/%3E%3Crect x='22' y='34' width='7' height='34' rx='1' fill='rgba(127%2C140%2C141%2C.09)'/%3E%3Crect x='31' y='38' width='9' height='30' rx='1' fill='rgba(127%2C140%2C141%2C.09)'/%3E%3Crect x='42' y='32' width='6' height='36' rx='1' fill='rgba(127%2C140%2C141%2C.08)'/%3E%3Crect x='50' y='36' width='8' height='32' rx='1' fill='rgba(127%2C140%2C141%2C.09)'/%3E%3Crect x='60' y='40' width='7' height='28' rx='1' fill='rgba(127%2C140%2C141%2C.09)'/%3E%3Cline x1='8' y1='68' x2='72' y2='68' stroke='rgba(127%2C140%2C141%2C.12)' stroke-width='1.5'/%3E%3C/svg%3E")`,
  },
];

export const CHARACTERS = [
  {
    id: 'jules-cesar',
    name: 'Jules César',
    dates: '100 — 44 av. J-C',
    universe: 'rome',
    tags: ['rome', 'conquerants', 'destins-tragiques', 'top10'],
    birth_year: -100,
    is_premium: false,
    isNew: false,
    duration: '1:02',
    youtubeId: null,
    img: 'https://picsum.photos/seed/jules-cesar-portrait/400/600',
    heroImg: 'https://picsum.photos/seed/rome-colosseum/1600/900',
    bio: "Général et homme d'État romain, Jules César transforma la République en Empire par la force de son génie militaire et politique. Ses conquêtes des Gaules étendirent Rome jusqu'aux confins de l'Europe, forgeant une légende qui résonne encore deux millénaires plus tard. Assassiné aux Ides de Mars 44 av. J-C, il devint le symbole éternel du pouvoir absolu et de la trahison.",
  },
  {
    id: 'marie-antoinette',
    name: 'Marie-Antoinette',
    dates: '1755 — 1793',
    universe: 'rois-france',
    tags: ['rois', 'femmes', 'destins-tragiques', 'top10', 'nouveau'],
    birth_year: 1755,
    is_premium: false,
    isNew: true,
    duration: '0:58',
    youtubeId: null,
    img: 'https://picsum.photos/seed/marie-antoinette-portrait/400/600',
    heroImg: null,
    bio: "Archiduchesse d'Autriche devenue reine de France à dix-neuf ans, Marie-Antoinette incarna l'éclat et les excès de Versailles dans une époque de bouleversements. Son destin bascula avec la Révolution française, transformant la reine en symbole de l'Ancien Régime aux yeux d'un peuple affamé. Guillotinée en 1793, elle laisse une image ambivalente, entre victime d'un système et actrice de sa propre tragédie.",
  },
  {
    id: 'louis-xvi',
    name: 'Louis XVI',
    dates: '1754 — 1793',
    universe: 'rois-france',
    tags: ['rois', 'destins-tragiques', 'top10'],
    birth_year: 1754,
    is_premium: false,
    isNew: false,
    duration: '0:55',
    youtubeId: null,
    img: 'https://picsum.photos/seed/louis-xvi-portrait/400/600',
    heroImg: null,
    bio: "Dernier roi de France de l'Ancien Régime, Louis XVI accéda au trône dans un royaume au bord de la banqueroute et de la révolte sociale. Homme sincère mais indécis, il tenta des réformes sans pouvoir endiguer la vague révolutionnaire qui balaya son règne. Jugé et décapité en janvier 1793, il reste le symbole d'une monarchie incapable de se réinventer face au souffle de l'Histoire.",
  },
  {
    id: 'louis-xiv',
    name: 'Louis XIV',
    dates: '1638 — 1715',
    universe: 'rois-france',
    tags: ['rois', 'top10'],
    birth_year: 1638,
    is_premium: false,
    isNew: false,
    duration: '1:05',
    youtubeId: null,
    img: 'https://picsum.photos/seed/louis-xiv-portrait/400/600',
    heroImg: null,
    bio: "Surnommé le Roi-Soleil, Louis XIV régna soixante-douze ans sur la France, le règne le plus long de l'histoire monarchique européenne. Il fit de Versailles le centre du monde civilisé, concentrant toute l'autorité en sa personne et imposant la grandeur française à l'Europe entière. Son absolutisme rayonnant redessina la carte politique du continent tout en façonnant une culture et un art qui influencent encore notre époque.",
  },
  {
    id: 'charlemagne',
    name: 'Charlemagne',
    dates: '742 — 814',
    universe: 'rois-france',
    tags: ['rois', 'conquerants'],
    birth_year: 742,
    is_premium: false,
    isNew: false,
    duration: '1:00',
    youtubeId: null,
    img: 'https://picsum.photos/seed/charlemagne-portrait/400/600',
    heroImg: null,
    bio: "Roi des Francs puis premier Empereur d'Occident couronné en l'an 800, Charlemagne unifia une grande partie de l'Europe sous sa bannière par la force des armes et de la foi chrétienne. Il entreprit une renaissance culturelle sans précédent, favorisant l'éducation et les arts dans un monde sorti à peine des ténèbres du Haut Moyen Âge. Père de l'Europe moderne selon certains historiens, son empire posa les fondations des nations françaises et allemandes.",
  },
  {
    id: 'catherine-de-medicis',
    name: 'Catherine de Médicis',
    dates: '1519 — 1589',
    universe: 'femmes-pouvoir',
    tags: ['femmes', 'top10', 'defie-epoque'],
    birth_year: 1519,
    is_premium: false,
    isNew: false,
    duration: '0:57',
    youtubeId: null,
    img: 'https://picsum.photos/seed/catherine-de-medicis-portrait/400/600',
    heroImg: null,
    bio: "Reine puis régente de France, Catherine de Médicis gouverna dans l'ombre et dans la lumière pendant plus de trente ans, manœuvrant avec habileté entre protestants et catholiques dans une France déchirée par les guerres de religion. Femme de culture héritière de la Renaissance florentine, elle introduisit le ballet à la cour de France et protégea les arts avec une passion éclairée. Sa responsabilité dans le massacre de la Saint-Barthélemy reste l'une des questions les plus débattues de l'historiographie française.",
  },
  {
    id: 'cleopatre',
    name: 'Cléopâtre',
    dates: '69 — 30 av. J-C',
    universe: 'femmes-pouvoir',
    tags: ['femmes', 'top10', 'defie-epoque', 'destins-tragiques'],
    birth_year: -69,
    is_premium: false,
    isNew: false,
    duration: '1:03',
    youtubeId: null,
    img: 'https://picsum.photos/seed/cleopatre-portrait/400/600',
    heroImg: null,
    bio: "Dernière souveraine du royaume ptolémaïque d'Égypte, Cléopâtre VII fut une reine d'une intelligence politique exceptionnelle, maîtrisant neuf langues et les subtilités de la diplomatie méditerranéenne. Ses alliances avec Jules César puis Marc Antoine représentèrent une stratégie lucide pour préserver l'indépendance égyptienne face à la puissance romaine grandissante. Sa mort volontaire à trente-neuf ans, après la défaite d'Actium, clôtura l'ère des pharaons et ouvrit celle de la domination romaine sur l'Orient.",
  },
  {
    id: 'jeanne-darc',
    name: "Jeanne d'Arc",
    dates: '1412 — 1431',
    universe: 'femmes-pouvoir',
    tags: ['femmes', 'destins-tragiques', 'defie-epoque', 'top10'],
    birth_year: 1412,
    is_premium: false,
    isNew: false,
    duration: '0:59',
    youtubeId: null,
    img: 'https://picsum.photos/seed/jeanne-darc-portrait/400/600',
    heroImg: null,
    bio: "Jeune paysanne lorraine guidée par des voix célestes, Jeanne d'Arc prit la tête des armées françaises à dix-sept ans et renversa le cours de la guerre de Cent Ans en faisant sacrer Charles VII à Reims. Capturée par les Bourguignons puis vendue aux Anglais, elle fut jugée pour hérésie et brûlée vive à Rouen à l'âge de dix-neuf ans. Réhabilitée en 1456 et canonisée en 1920, elle demeure le symbole intemporel du courage féminin et de l'identité nationale française.",
  },
  {
    id: 'tomoe-gozen',
    name: 'Tomoe Gozen',
    dates: 'v. 1157 — v. 1247',
    universe: 'legendes-asie',
    tags: ['asie', 'femmes', 'defie-epoque'],
    birth_year: 1157,
    is_premium: false,
    isNew: false,
    duration: '0:54',
    youtubeId: null,
    img: 'https://picsum.photos/seed/tomoe-gozen-portrait/400/600',
    heroImg: null,
    bio: "Onna-musha légendaire du Japon médiéval, Tomoe Gozen fut l'une des rares femmes samouraïs à combattre aux côtés des plus grands guerriers de son époque. Célèbre pour sa beauté autant que pour sa maîtrise du katana et du tir à l'arc, elle accompagna le seigneur Minamoto no Yoshinaka dans ses batailles contre le clan Taira. Son histoire, transmise dans le Heike Monogatari, en fait l'archétype de la femme guerrière dans la culture japonaise.",
  },
  {
    id: 'anne-bonny',
    name: 'Anne Bonny',
    dates: '1697 — v. 1782',
    universe: 'legendes-mers',
    tags: ['mers', 'femmes', 'defie-epoque'],
    birth_year: 1697,
    is_premium: false,
    isNew: false,
    duration: '0:52',
    youtubeId: null,
    img: 'https://picsum.photos/seed/anne-bonny-portrait/400/600',
    heroImg: null,
    bio: "Née en Irlande et élevée en Caroline du Sud, Anne Bonny brisa toutes les conventions de son époque en rejoignant la piraterie des Caraïbes aux côtés du célèbre Calico Jack. Redoutée par ses ennemis pour sa férocité au combat, elle fut l'une des rares femmes pirates reconnues de l'âge d'or de la piraterie. Capturée en 1720, elle échappa mystérieusement à la pendaison et sa destinée finale reste enveloppée dans le mystère et la légende.",
  },
  {
    id: 'magellan',
    name: 'Magellan',
    dates: '1480 — 1521',
    universe: 'legendes-mers',
    tags: ['mers', 'conquerants', 'destins-tragiques'],
    birth_year: 1480,
    is_premium: false,
    isNew: false,
    duration: '1:01',
    youtubeId: null,
    img: 'https://picsum.photos/seed/magellan-portrait/400/600',
    heroImg: null,
    bio: "Navigateur portugais au service de l'Espagne, Ferdinand de Magellan organisa la première circumnavigation de la Terre, prouvant définitivement la rotondité du globe et l'existence d'un passage vers les Indes par l'ouest. Son périple de trois ans à travers des mers inconnues fut une épopée de courage et d'obstination, traversant les tempêtes du détroit qui porte aujourd'hui son nom. Tué aux Philippines lors de la bataille de Mactan en 1521, il ne vit jamais l'achèvement de son œuvre colossale.",
  },
  {
    id: 'gengis-khan',
    name: 'Gengis Khan',
    dates: '1162 — 1227',
    universe: 'legendes-asie',
    tags: ['asie', 'conquerants'],
    birth_year: 1162,
    is_premium: false,
    isNew: false,
    duration: '1:04',
    youtubeId: null,
    img: 'https://picsum.photos/seed/gengis-khan-portrait/400/600',
    heroImg: null,
    bio: "Fondateur et premier Grand Khan de l'Empire mongol, Gengis Khan unifia les tribus nomades de la steppe pour créer le plus grand empire continu de l'histoire humaine, s'étendant du Pacifique à la Caspienne. Stratège militaire de génie, il révolutionna l'art de la guerre par la mobilité de sa cavalerie et une organisation tactique d'une redoutable efficacité. Son héritage dépasse la conquête : il favorisa le commerce sur la Route de la Soie et permit un échange culturel sans précédent entre l'Orient et l'Occident.",
  },
  {
    id: 'george-washington',
    name: 'George Washington',
    dates: '1732 — 1799',
    universe: 'philosophes',
    tags: ['defie-epoque', 'top10'],
    birth_year: 1732,
    is_premium: false,
    isNew: false,
    duration: '0:56',
    youtubeId: null,
    img: 'https://picsum.photos/seed/george-washington-portrait/400/600',
    heroImg: null,
    bio: "Premier président des États-Unis d'Amérique, George Washington commanda les forces révolutionnaires lors de la guerre d'Indépendance et façonna les fondements d'une nouvelle nation fondée sur les principes des Lumières. Son refus de briguer un troisième mandat présidentiel établit un précédent démocratique fondamental qui définit encore la démocratie américaine. Vénéré comme le Père de la Nation, il incarne l'idéal républicain et l'abnégation au service de la chose publique.",
  },
  {
    id: 'socrate',
    name: 'Socrate',
    dates: '470 — 399 av. J-C',
    universe: 'philosophes',
    tags: ['philo', 'destins-tragiques'],
    birth_year: -470,
    is_premium: false,
    isNew: false,
    duration: '0:53',
    youtubeId: null,
    img: 'https://picsum.photos/seed/socrate-portrait/400/600',
    heroImg: null,
    bio: "Philosophe athénien considéré comme le père de la philosophie occidentale, Socrate n'écrivit jamais une ligne mais révolutionna la pensée humaine par sa méthode dialectique, l'ironie et la maïeutique. Accusé de corrompre la jeunesse et d'impiété envers les dieux de la cité, il fut condamné à mort par le tribunal athénien et choisit de boire la ciguë plutôt que de renier ses convictions. Sa mort volontaire, immortalisée par son disciple Platon, fit de lui le martyr éternel de la liberté de pensée.",
  },
  {
    id: 'meduse',
    name: 'Méduse',
    dates: 'Temps mythiques',
    universe: 'mythologie-grecque',
    tags: ['mythologie-grecque'],
    birth_year: null,
    is_premium: true,
    isNew: false,
    duration: '0:48',
    youtubeId: null,
    img: 'https://picsum.photos/seed/meduse-portrait/400/600',
    heroImg: null,
    bio: "Gorgone au regard pétrifiant, Méduse fut jadis une belle mortelle dont Poséidon s'éprit, avant qu'Athéna ne la transforme en monstre terrible aux cheveux de serpents. Seul Persée, guidé par les dieux et armé du bouclier-miroir d'Athéna, parvint à la décapiter sans croiser son regard fatal. De son sang jaillit Pégase, le cheval ailé, et sa tête tranchée devint l'une des armes les plus redoutables de la mythologie grecque, capable encore de pétrifier ses ennemis.",
  },
];

export function getStaticTransition(from, to) {
  if (!from || !to) return '';
  const yearA = from.birth_year;
  const yearB = to.birth_year;
  if (yearA !== null && yearB !== null) {
    const diff = Math.abs(yearB - yearA);
    const centuries = Math.round(diff / 100);
    if (centuries >= 2) {
      return `Entre ${from.name} et ${to.name} — ${centuries} siècles d'Histoire, deux destins façonnés par leur époque.`;
    }
  }
  return `De ${from.name} à ${to.name} — deux figures inoubliables gravées dans la mémoire de l'humanité.`;
}
